@baseURL = http://localhost:3000

### Rota pública
GET {{baseURL}}/events
Content-Type: application/json

### Login do usuário
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "usuario@ifrs.edu.br",
 "password": "123456"
}

### Login do admin
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "admin123"
}

### Acesso à área admin
GET {{baseURL}}/protected/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5MzU2MzM4LCJleHAiOjE3NTkzNTk5Mzh9.uIQ2lvMcsvxlcpS8UZKw0hH0YQTeUBjsJsec1rvBQQk

